name: Compilar Mod Fabric 1.21.1

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Descomprimir archivos del mod
        run: |
          unzip -o mi_mod_realista.zip
          if [ -d "mi_mod_realista" ]; then cp -rn mi_mod_realista/* .; fi

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Permisos de ejecucion
        run: chmod +x gradlew

      - name: Compilar con Gradle
        run: ./gradlew build

      - name: Guardar archivo JAR
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
